name: La Danze UI CI/CD

on:
  push:
    # Run on all branches excepted gh-pages
    branches:
      - '**'
      - '!gh-pages'
    # Run on all version tags 
    tags:
      - 'v*.*.*'
    # Don't run when files commited are only doc files
    paths-ignore:
      - '**.md'
      - '.github/doc/**'
  pull_request:
    # Run only on main branch
    branches:
      - 'main'
    # Run on all version tags   
    tags:
      - 'v*.*.*'
    # Don't run when files commited are only doc files  
    paths-ignore:
      - '**.md'
      - '.github/doc/**'

jobs:

  # Build and Test
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    # ---------------------------------- 
    #           Yarn cache 
    # ----------------------------------   
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    # ---------------------------------- 
    #           Yarn cache 
    # ----------------------------------          

    # Install dependencies
    - name: INSTALL
      run: yarn install --prefer-offline

    # Build all packages (lib, demo, doc)
    - name: BUILD
      run: yarn build:ci

    # Test lib package
    - name: TEST
      run: yarn test:ci:lib

    # ---------------------------------- 
    #         Upload artifacts 
    # ----------------------------------  
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: packages/lib/coverage/lcov.info

    - uses: actions/upload-artifact@v2
      with:
        name: lib-dist
        path: packages/lib/dist/

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/
    # ---------------------------------- 
    #         Upload artifacts 
    # ----------------------------------         


  # Sonnar scan (lib package)  
  sonarcloud:
    name: Sonar
    needs: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    # ---------------------------------- 
    #    Download coverage artifacts 
    # ---------------------------------- 
    - uses: actions/download-artifact@v2
      with:
        name: coverage
    # ---------------------------------- 
    #    Download coverage artifacts 
    # ---------------------------------- 

    # Run sonar scan
    - name: SONAR
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  # Release lib package
  release:
    name: Release
    # Launch only on main branch
    # Skip if there is a version tag (this job created the tag, so we won't rerun it)
    if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    # ---------------------------------- 
    #           Yarn cache 
    # ----------------------------------
    - uses: actions/download-artifact@v2
      with:
        name: lib-dist
        path: packages/lib/dist/

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    # ---------------------------------- 
    #           Yarn cache 
    # ----------------------------------

    # Install dependencies  
    - name: INSTALL
      run: yarn install --prefer-offline

    # Copy README.md to lib package (for npm)  
    - name: COPY README.md
      run: cp README.md packages/lib/

    # Release  
    - name: RELEASE
      run: yarn semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}   
        GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}   
        GIT_COMMITTER_NAME: ${{ secrets.GIT_AUTHOR_NAME }}   
        GIT_COMMITTER_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}   


  # Deploy to gh pages
  deploy:
    name: Deploy
    # Launch only on version tags
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    # ---------------------------------- 
    #     Download dist artifacts 
    # ----------------------------------
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist/
    # ---------------------------------- 
    #     Download dist artifacts 
    # ----------------------------------

    # Deploy dist folder to gh pages  
    - name: DEPLOY
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./dist
        user_name: ${{ secrets.GIT_AUTHOR_NAME }} 
        user_email: ${{ secrets.GIT_AUTHOR_EMAIL }}