# This workflow is made to deploy docs and demo to github pages
# So it focuses only on packages/la-danze-ui-docs and packages/la-danze-ui-demo
name: Github Pages

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  # Build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      # ----------------------------------
      #           Yarn cache
      # ----------------------------------
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # ----------------------------------
      #           Yarn cache
      # ----------------------------------

      # Install dependencies
      - name: INSTALL
        # Install dependencies only if cache was not found to accelerate workflow
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      # Build all packages (la-danze-ui, la-danze-ui-demo, la-danze-ui-docs)
      # We also build packages/la-danze-ui because it is used in packages/la-danze-ui-demo
      - name: BUILD
        run: yarn build:ci

      # ----------------------------------
      #         Upload artifacts
      # ----------------------------------
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
      # ----------------------------------
      #         Upload artifacts
      # ----------------------------------

  # Deploy to gh pages
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    # Manual deployment
    # See https://devblogs.microsoft.com/devops/i-need-manual-approvers-for-github-actions-and-i-got-them-now/
    environment:
      name: pchmn.github.io/la-danze-ui
      url: https://pchmn.github.io/la-danze-ui/
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      # ----------------------------------
      #     Download dist artifacts
      # ----------------------------------
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      # ----------------------------------
      #     Download dist artifacts
      # ----------------------------------

      # Deploy dist folder to gh pages
      - name: DEPLOY
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: ${{ secrets.GIT_AUTHOR_NAME }}
          user_email: ${{ secrets.GIT_AUTHOR_EMAIL }}
